import type { GiftCategory, GiftPriority, MultilingualText } from '@/types/gift'

export interface DefaultGiftTemplate {
  id: string
  name: MultilingualText
  description: MultilingualText
  category: GiftCategory
  priority: GiftPriority
  priceRange: string
  quantityTotal: number
}

export const DEFAULT_GIFT_TEMPLATES: DefaultGiftTemplate[] = [
  // ============================================
  // HOME CATEGORY (18 items)
  // ============================================
  {
    id: 'bedding-set',
    name: {
      en: 'Bedding Set',
      ms: 'Set Cadar',
      zh: '床上用品套装',
      ta: 'படுக்கை தொகுப்பு',
    },
    description: {
      en: 'Complete bedding set with comforter, sheets, and pillowcases',
      ms: 'Set cadar lengkap dengan comforter, cadar dan sarung bantal',
      zh: '包含被子、床单和枕套的完整床上用品套装',
      ta: 'போர்வை, விரிப்புகள் மற்றும் தலையணை உறைகளுடன் முழுமையான படுக்கை தொகுப்பு',
    },
    category: 'home',
    priority: 'high',
    priceRange: 'RM200 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'towel-set',
    name: {
      en: 'Towel Set',
      ms: 'Set Tuala',
      zh: '毛巾套装',
      ta: 'துண்டு தொகுப்பு',
    },
    description: {
      en: 'Premium bath towel set including bath towels, hand towels, and face towels',
      ms: 'Set tuala mandi premium termasuk tuala mandi, tuala tangan dan tuala muka',
      zh: '高档浴巾套装，包括浴巾、手巾和面巾',
      ta: 'குளியல் துண்டுகள், கை துண்டுகள் மற்றும் முக துண்டுகள் உள்ளிட்ட பிரீமியம் குளியல் துண்டு தொகுப்பு',
    },
    category: 'home',
    priority: 'medium',
    priceRange: 'RM100 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'vacuum-cleaner',
    name: {
      en: 'Vacuum Cleaner',
      ms: 'Pembersih Vakum',
      zh: '吸尘器',
      ta: 'வெற்றிட சுத்திகரிப்பான்',
    },
    description: {
      en: 'Powerful vacuum cleaner for easy home cleaning',
      ms: 'Pembersih vakum berkuasa untuk pembersihan rumah yang mudah',
      zh: '强力吸尘器，轻松清洁家居',
      ta: 'எளிதான வீட்டு சுத்தம் செய்ய சக்திவாய்ந்த வெற்றிட சுத்திகரிப்பான்',
    },
    category: 'home',
    priority: 'high',
    priceRange: 'RM300 - RM800',
    quantityTotal: 1,
  },
  {
    id: 'iron-ironing-board',
    name: {
      en: 'Iron & Ironing Board',
      ms: 'Seterika & Papan Seterika',
      zh: '熨斗和熨衣板',
      ta: 'இஸ்திரி மற்றும் இஸ்திரி பலகை',
    },
    description: {
      en: 'Steam iron with sturdy ironing board for wrinkle-free clothes',
      ms: 'Seterika wap dengan papan seterika kukuh untuk pakaian tanpa kedutan',
      zh: '蒸汽熨斗配坚固的熨衣板，让衣物无皱褶',
      ta: 'சுருக்கமில்லாத ஆடைகளுக்கான உறுதியான இஸ்திரி பலகையுடன் நீராவி இஸ்திரி',
    },
    category: 'home',
    priority: 'medium',
    priceRange: 'RM150 - RM400',
    quantityTotal: 1,
  },
  {
    id: 'wall-clock',
    name: {
      en: 'Wall Clock',
      ms: 'Jam Dinding',
      zh: '挂钟',
      ta: 'சுவர் கடிகாரம்',
    },
    description: {
      en: 'Elegant wall clock to decorate your new home',
      ms: 'Jam dinding elegan untuk menghias rumah baru anda',
      zh: '优雅的挂钟装饰您的新家',
      ta: 'உங்கள் புதிய வீட்டை அலங்கரிக்க நேர்த்தியான சுவர் கடிகாரம்',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM50 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'storage-containers',
    name: {
      en: 'Storage Container Set',
      ms: 'Set Bekas Penyimpanan',
      zh: '收纳容器套装',
      ta: 'சேமிப்பு கொள்கலன் தொகுப்பு',
    },
    description: {
      en: 'Stackable storage containers for organized living',
      ms: 'Bekas penyimpanan boleh susun untuk kehidupan tersusun',
      zh: '可叠放收纳容器，让生活井井有条',
      ta: 'ஒழுங்கமைக்கப்பட்ட வாழ்க்கைக்கான அடுக்கக்கூடிய சேமிப்பு கொள்கலன்கள்',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM80 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'curtains',
    name: {
      en: 'Curtains',
      ms: 'Langsir',
      zh: '窗帘',
      ta: 'திரைச்சீலைகள்',
    },
    description: {
      en: 'Beautiful curtains to complement your home decor',
      ms: 'Langsir cantik untuk melengkapi hiasan rumah anda',
      zh: '美丽的窗帘，为您的家居装饰增添光彩',
      ta: 'உங்கள் வீட்டு அலங்காரத்தை நிறைவு செய்ய அழகான திரைச்சீலைகள்',
    },
    category: 'home',
    priority: 'medium',
    priceRange: 'RM150 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'floor-mat-set',
    name: {
      en: 'Floor Mat Set',
      ms: 'Set Alas Lantai',
      zh: '地垫套装',
      ta: 'தரை பாய் தொகுப்பு',
    },
    description: {
      en: 'Non-slip floor mats for bathroom and kitchen',
      ms: 'Alas lantai anti-gelincir untuk bilik mandi dan dapur',
      zh: '浴室和厨房防滑地垫',
      ta: 'குளியலறை மற்றும் சமையலறைக்கான நழுவாத தரை பாய்கள்',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM50 - RM150',
    quantityTotal: 1,
  },
  {
    id: 'pillow-set',
    name: {
      en: 'Pillow Set',
      ms: 'Set Bantal',
      zh: '枕头套装',
      ta: 'தலையணை தொகுப்பு',
    },
    description: {
      en: 'Quality pillows for comfortable sleep',
      ms: 'Bantal berkualiti untuk tidur yang selesa',
      zh: '优质枕头，让您睡得舒适',
      ta: 'வசதியான தூக்கத்திற்கான தரமான தலையணைகள்',
    },
    category: 'home',
    priority: 'medium',
    priceRange: 'RM80 - RM250',
    quantityTotal: 1,
  },
  {
    id: 'throw-blanket',
    name: {
      en: 'Throw Blanket',
      ms: 'Selimut',
      zh: '毛毯',
      ta: 'போர்வை',
    },
    description: {
      en: 'Cozy throw blanket for living room or bedroom',
      ms: 'Selimut selesa untuk ruang tamu atau bilik tidur',
      zh: '客厅或卧室的舒适毛毯',
      ta: 'வாழ்க்கை அறை அல்லது படுக்கையறைக்கான வசதியான போர்வை',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM50 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'laundry-basket',
    name: {
      en: 'Laundry Basket',
      ms: 'Bakul Pakaian',
      zh: '洗衣篮',
      ta: 'சலவை கூடை',
    },
    description: {
      en: 'Sturdy laundry basket for organizing clothes',
      ms: 'Bakul pakaian kukuh untuk menyusun pakaian',
      zh: '坚固的洗衣篮，用于整理衣物',
      ta: 'ஆடைகளை ஒழுங்கமைக்க உறுதியான சலவை கூடை',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM30 - RM100',
    quantityTotal: 1,
  },
  {
    id: 'shoe-rack',
    name: {
      en: 'Shoe Rack',
      ms: 'Rak Kasut',
      zh: '鞋架',
      ta: 'காலணி அலமாரி',
    },
    description: {
      en: 'Multi-tier shoe rack for organized entryway',
      ms: 'Rak kasut berbilang tingkat untuk pintu masuk yang tersusun',
      zh: '多层鞋架，让入口整洁有序',
      ta: 'ஒழுங்கமைக்கப்பட்ட நுழைவாயிலுக்கான பல அடுக்கு காலணி அலமாரி',
    },
    category: 'home',
    priority: 'medium',
    priceRange: 'RM50 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'full-length-mirror',
    name: {
      en: 'Full-Length Mirror',
      ms: 'Cermin Penuh',
      zh: '全身镜',
      ta: 'முழு நீள கண்ணாடி',
    },
    description: {
      en: 'Elegant full-length mirror for bedroom or dressing area',
      ms: 'Cermin penuh elegan untuk bilik tidur atau ruang berpakaian',
      zh: '卧室或更衣区的优雅全身镜',
      ta: 'படுக்கையறை அல்லது உடை அணியும் பகுதிக்கான நேர்த்தியான முழு நீள கண்ணாடி',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM100 - RM400',
    quantityTotal: 1,
  },
  {
    id: 'picture-frames',
    name: {
      en: 'Picture Frame Set',
      ms: 'Set Bingkai Gambar',
      zh: '相框套装',
      ta: 'படச்சட்ட தொகுப்பு',
    },
    description: {
      en: 'Set of picture frames to display wedding and family photos',
      ms: 'Set bingkai gambar untuk mempamerkan foto perkahwinan dan keluarga',
      zh: '用于展示婚礼和家庭照片的相框套装',
      ta: 'திருமண மற்றும் குடும்ப புகைப்படங்களை காட்சிப்படுத்த படச்சட்ட தொகுப்பு',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM50 - RM150',
    quantityTotal: 1,
  },
  {
    id: 'bathroom-accessories',
    name: {
      en: 'Bathroom Accessories Set',
      ms: 'Set Aksesori Bilik Mandi',
      zh: '浴室配件套装',
      ta: 'குளியலறை பாகங்கள் தொகுப்பு',
    },
    description: {
      en: 'Matching bathroom accessories including soap dispenser, toothbrush holder, and more',
      ms: 'Aksesori bilik mandi sepadan termasuk dispenser sabun, pemegang berus gigi dan banyak lagi',
      zh: '配套浴室配件，包括皂液器、牙刷架等',
      ta: 'சோப்பு விநியோகி, பல் துலக்கி வைப்பான் மற்றும் பல உள்ளிட்ட பொருத்தமான குளியலறை பாகங்கள்',
    },
    category: 'home',
    priority: 'medium',
    priceRange: 'RM80 - RM250',
    quantityTotal: 1,
  },
  {
    id: 'clothes-hanger-set',
    name: {
      en: 'Clothes Hanger Set',
      ms: 'Set Penyangkut Pakaian',
      zh: '衣架套装',
      ta: 'ஆடை தொங்கி தொகுப்பு',
    },
    description: {
      en: 'Quality wooden or velvet hangers for wardrobe organization',
      ms: 'Penyangkut kayu atau baldu berkualiti untuk penyusunan almari',
      zh: '优质木质或天鹅绒衣架，用于衣柜整理',
      ta: 'அலமாரி அமைப்புக்கான தரமான மர அல்லது வெல்வெட் தொங்கிகள்',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM30 - RM100',
    quantityTotal: 1,
  },
  {
    id: 'bedside-lamp',
    name: {
      en: 'Bedside Lamp',
      ms: 'Lampu Sisi Katil',
      zh: '床头灯',
      ta: 'படுக்கையருகே விளக்கு',
    },
    description: {
      en: 'Elegant bedside lamp for ambient lighting',
      ms: 'Lampu sisi katil elegan untuk pencahayaan ambien',
      zh: '优雅的床头灯，营造氛围照明',
      ta: 'சுற்றுப்புற வெளிச்சத்திற்கான நேர்த்தியான படுக்கையருகே விளக்கு',
    },
    category: 'home',
    priority: 'low',
    priceRange: 'RM50 - RM200',
    quantityTotal: 2,
  },

  // ============================================
  // KITCHEN CATEGORY (20 items)
  // ============================================
  {
    id: 'rice-cooker',
    name: {
      en: 'Rice Cooker',
      ms: 'Periuk Nasi',
      zh: '电饭煲',
      ta: 'சோறு சமைக்கும் கருவி',
    },
    description: {
      en: 'Multi-function rice cooker for perfect rice every time',
      ms: 'Periuk nasi pelbagai fungsi untuk nasi sempurna setiap kali',
      zh: '多功能电饭煲，每次都能煮出完美的米饭',
      ta: 'ஒவ்வொரு முறையும் சரியான சோறுக்கான பல்-செயல்பாட்டு சோறு சமைக்கும் கருவி',
    },
    category: 'kitchen',
    priority: 'high',
    priceRange: 'RM150 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'air-fryer',
    name: {
      en: 'Air Fryer',
      ms: 'Penggoreng Udara',
      zh: '空气炸锅',
      ta: 'ஏர் ஃப்ரையர்',
    },
    description: {
      en: 'Healthy cooking with little to no oil required',
      ms: 'Masakan sihat dengan sedikit atau tanpa minyak',
      zh: '健康烹饪，少油或无油',
      ta: 'குறைந்த அல்லது எண்ணெய் இல்லாமல் ஆரோக்கியமான சமையல்',
    },
    category: 'kitchen',
    priority: 'high',
    priceRange: 'RM200 - RM600',
    quantityTotal: 1,
  },
  {
    id: 'blender',
    name: {
      en: 'Blender',
      ms: 'Pengisar',
      zh: '搅拌机',
      ta: 'கலப்பான்',
    },
    description: {
      en: 'Powerful blender for smoothies, soups, and more',
      ms: 'Pengisar berkuasa untuk smoothie, sup dan banyak lagi',
      zh: '强力搅拌机，可制作冰沙、汤等',
      ta: 'ஸ்மூத்திகள், சூப்கள் மற்றும் பலவற்றிற்கான சக்திவாய்ந்த கலப்பான்',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM100 - RM400',
    quantityTotal: 1,
  },
  {
    id: 'cookware-set',
    name: {
      en: 'Cookware Set',
      ms: 'Set Peralatan Memasak',
      zh: '厨具套装',
      ta: 'சமையல் பாத்திர தொகுப்பு',
    },
    description: {
      en: 'Complete set of pots and pans for everyday cooking',
      ms: 'Set lengkap periuk dan kuali untuk masakan harian',
      zh: '日常烹饪所需的锅具套装',
      ta: 'தினசரி சமையலுக்கான பாத்திரங்கள் மற்றும் கடாய்களின் முழுமையான தொகுப்பு',
    },
    category: 'kitchen',
    priority: 'high',
    priceRange: 'RM300 - RM800',
    quantityTotal: 1,
  },
  {
    id: 'dinner-set',
    name: {
      en: 'Dinner Set',
      ms: 'Set Pinggan Mangkuk',
      zh: '餐具套装',
      ta: 'இரவு உணவு தொகுப்பு',
    },
    description: {
      en: 'Elegant dinner set with plates, bowls, and serving dishes',
      ms: 'Set pinggan mangkuk elegan dengan pinggan, mangkuk dan hidangan',
      zh: '优雅的餐具套装，包括盘子、碗和餐盘',
      ta: 'தட்டுகள், கிண்ணங்கள் மற்றும் பரிமாறும் பாத்திரங்களுடன் நேர்த்தியான இரவு உணவு தொகுப்பு',
    },
    category: 'kitchen',
    priority: 'high',
    priceRange: 'RM150 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'electric-kettle',
    name: {
      en: 'Electric Kettle',
      ms: 'Cerek Elektrik',
      zh: '电热水壶',
      ta: 'மின் கெட்டில்',
    },
    description: {
      en: 'Fast-boiling electric kettle for hot beverages',
      ms: 'Cerek elektrik cepat mendidih untuk minuman panas',
      zh: '快速沸腾的电热水壶，用于热饮',
      ta: 'சூடான பானங்களுக்கான வேகமாக கொதிக்கும் மின் கெட்டில்',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM50 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'toaster',
    name: {
      en: 'Toaster',
      ms: 'Pembakar Roti',
      zh: '烤面包机',
      ta: 'டோஸ்டர்',
    },
    description: {
      en: 'Classic toaster for perfect toast every morning',
      ms: 'Pembakar roti klasik untuk roti bakar sempurna setiap pagi',
      zh: '经典烤面包机，每天早晨都能烤出完美的吐司',
      ta: 'ஒவ்வொரு காலையும் சரியான டோஸ்ட்டுக்கான கிளாசிக் டோஸ்டர்',
    },
    category: 'kitchen',
    priority: 'low',
    priceRange: 'RM50 - RM150',
    quantityTotal: 1,
  },
  {
    id: 'food-container-set',
    name: {
      en: 'Food Container Set',
      ms: 'Set Bekas Makanan',
      zh: '食物容器套装',
      ta: 'உணவு கொள்கலன் தொகுப்பு',
    },
    description: {
      en: 'Airtight food containers for meal prep and storage',
      ms: 'Bekas makanan kedap udara untuk penyediaan dan penyimpanan makanan',
      zh: '密封食物容器，用于备餐和储存',
      ta: 'உணவு தயாரிப்பு மற்றும் சேமிப்புக்கான காற்றுப்புகா உணவு கொள்கலன்கள்',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM50 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'knife-set',
    name: {
      en: 'Kitchen Knife Set',
      ms: 'Set Pisau Dapur',
      zh: '厨房刀具套装',
      ta: 'சமையலறை கத்தி தொகுப்பு',
    },
    description: {
      en: 'Professional knife set with various sizes for all cooking needs',
      ms: 'Set pisau profesional pelbagai saiz untuk semua keperluan memasak',
      zh: '专业刀具套装，各种尺寸满足所有烹饪需求',
      ta: 'அனைத்து சமையல் தேவைகளுக்கும் பல்வேறு அளவுகளில் தொழில்முறை கத்தி தொகுப்பு',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM100 - RM400',
    quantityTotal: 1,
  },
  {
    id: 'pressure-cooker',
    name: {
      en: 'Pressure Cooker',
      ms: 'Periuk Tekanan',
      zh: '压力锅',
      ta: 'பிரஷர் குக்கர்',
    },
    description: {
      en: 'Electric pressure cooker for fast and convenient cooking',
      ms: 'Periuk tekanan elektrik untuk masakan cepat dan mudah',
      zh: '电压力锅，快速方便烹饪',
      ta: 'வேகமான மற்றும் வசதியான சமையலுக்கான மின் பிரஷர் குக்கர்',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM200 - RM600',
    quantityTotal: 1,
  },
  {
    id: 'microwave-oven',
    name: {
      en: 'Microwave Oven',
      ms: 'Ketuhar Gelombang Mikro',
      zh: '微波炉',
      ta: 'மைக்ரோவேவ் அடுப்பு',
    },
    description: {
      en: 'Versatile microwave oven for quick heating and cooking',
      ms: 'Ketuhar gelombang mikro serbaguna untuk pemanasan dan masakan cepat',
      zh: '多功能微波炉，快速加热和烹饪',
      ta: 'விரைவான வெப்பமாக்கல் மற்றும் சமைப்பதற்கான பல்துறை மைக்ரோவேவ் அடுப்பு',
    },
    category: 'kitchen',
    priority: 'high',
    priceRange: 'RM200 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'water-dispenser',
    name: {
      en: 'Water Dispenser',
      ms: 'Dispenser Air',
      zh: '饮水机',
      ta: 'தண்ணீர் விநியோகி',
    },
    description: {
      en: 'Hot and cold water dispenser for convenient drinking water',
      ms: 'Dispenser air panas dan sejuk untuk air minuman yang mudah',
      zh: '冷热水饮水机，方便饮用',
      ta: 'வசதியான குடிநீருக்கான சூடான மற்றும் குளிர்ந்த நீர் விநியோகி',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM200 - RM600',
    quantityTotal: 1,
  },
  {
    id: 'food-steamer',
    name: {
      en: 'Food Steamer',
      ms: 'Pengukus Makanan',
      zh: '蒸锅',
      ta: 'உணவு ஆவியில் வேகவைக்கும் கருவி',
    },
    description: {
      en: 'Electric food steamer for healthy cooking',
      ms: 'Pengukus makanan elektrik untuk masakan sihat',
      zh: '电蒸锅，健康烹饪',
      ta: 'ஆரோக்கியமான சமையலுக்கான மின் உணவு ஆவியில் வேகவைக்கும் கருவி',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM100 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'wok',
    name: {
      en: 'Wok',
      ms: 'Kuali',
      zh: '炒锅',
      ta: 'வோக்',
    },
    description: {
      en: 'High-quality wok for stir-frying and Asian cooking',
      ms: 'Kuali berkualiti tinggi untuk tumis dan masakan Asia',
      zh: '高品质炒锅，适合炒菜和亚洲烹饪',
      ta: 'வறுத்தல் மற்றும் ஆசிய சமையலுக்கான உயர்தர வோக்',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM80 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'baking-set',
    name: {
      en: 'Baking Set',
      ms: 'Set Membakar',
      zh: '烘焙套装',
      ta: 'பேக்கிங் தொகுப்பு',
    },
    description: {
      en: 'Complete baking set with trays, molds, and utensils',
      ms: 'Set membakar lengkap dengan dulang, acuan dan peralatan',
      zh: '完整的烘焙套装，包括烤盘、模具和器具',
      ta: 'தட்டுகள், அச்சுகள் மற்றும் பாத்திரங்களுடன் முழுமையான பேக்கிங் தொகுப்பு',
    },
    category: 'kitchen',
    priority: 'low',
    priceRange: 'RM100 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'glass-set',
    name: {
      en: 'Glass & Drinkware Set',
      ms: 'Set Gelas',
      zh: '玻璃杯套装',
      ta: 'கண்ணாடி தொகுப்பு',
    },
    description: {
      en: 'Elegant glass and drinkware set for serving beverages',
      ms: 'Set gelas elegan untuk menghidangkan minuman',
      zh: '优雅的玻璃杯套装，用于供应饮料',
      ta: 'பானங்களை பரிமாறுவதற்கான நேர்த்தியான கண்ணாடி தொகுப்பு',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM50 - RM200',
    quantityTotal: 1,
  },
  {
    id: 'cutlery-set',
    name: {
      en: 'Cutlery Set',
      ms: 'Set Sudu Garpu',
      zh: '餐具套装',
      ta: 'கட்லரி தொகுப்பு',
    },
    description: {
      en: 'Stainless steel cutlery set for dining',
      ms: 'Set sudu garpu keluli tahan karat untuk makan',
      zh: '不锈钢餐具套装',
      ta: 'உணவருந்துவதற்கான துருப்பிடிக்காத எஃகு கட்லரி தொகுப்பு',
    },
    category: 'kitchen',
    priority: 'medium',
    priceRange: 'RM80 - RM250',
    quantityTotal: 1,
  },
  {
    id: 'spice-rack',
    name: {
      en: 'Spice Rack',
      ms: 'Rak Rempah',
      zh: '调料架',
      ta: 'மசாலா அலமாரி',
    },
    description: {
      en: 'Organized spice rack with containers for kitchen',
      ms: 'Rak rempah tersusun dengan bekas untuk dapur',
      zh: '带容器的有序调料架',
      ta: 'சமையலறைக்கான கொள்கலன்களுடன் ஒழுங்கமைக்கப்பட்ட மசாலா அலமாரி',
    },
    category: 'kitchen',
    priority: 'low',
    priceRange: 'RM30 - RM100',
    quantityTotal: 1,
  },
  {
    id: 'serving-tray',
    name: {
      en: 'Serving Tray Set',
      ms: 'Set Dulang Hidangan',
      zh: '托盘套装',
      ta: 'பரிமாறும் தட்டு தொகுப்பு',
    },
    description: {
      en: 'Elegant serving trays for entertaining guests',
      ms: 'Dulang hidangan elegan untuk melayan tetamu',
      zh: '优雅的托盘套装，用于招待客人',
      ta: 'விருந்தினர்களை உபசரிக்க நேர்த்தியான பரிமாறும் தட்டுகள்',
    },
    category: 'kitchen',
    priority: 'low',
    priceRange: 'RM50 - RM150',
    quantityTotal: 1,
  },

  // ============================================
  // ELECTRONICS CATEGORY (12 items)
  // ============================================
  {
    id: 'smart-tv',
    name: {
      en: 'Smart TV',
      ms: 'TV Pintar',
      zh: '智能电视',
      ta: 'ஸ்மார்ட் டிவி',
    },
    description: {
      en: 'Smart TV with streaming capabilities for entertainment',
      ms: 'TV pintar dengan keupayaan penstriman untuk hiburan',
      zh: '具有流媒体功能的智能电视，提供娱乐',
      ta: 'பொழுதுபோக்கிற்கான ஸ்ட்ரீமிங் திறன்களுடன் ஸ்மார்ட் டிவி',
    },
    category: 'electronics',
    priority: 'high',
    priceRange: 'RM1000 - RM3000',
    quantityTotal: 1,
  },
  {
    id: 'standing-fan',
    name: {
      en: 'Standing Fan',
      ms: 'Kipas Berdiri',
      zh: '落地扇',
      ta: 'நிற்கும் விசிறி',
    },
    description: {
      en: 'Powerful standing fan with multiple speed settings',
      ms: 'Kipas berdiri berkuasa dengan pelbagai tetapan kelajuan',
      zh: '多档速度设置的强力落地扇',
      ta: 'பல வேக அமைப்புகளுடன் சக்திவாய்ந்த நிற்கும் விசிறி',
    },
    category: 'electronics',
    priority: 'medium',
    priceRange: 'RM100 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'air-purifier',
    name: {
      en: 'Air Purifier',
      ms: 'Penapis Udara',
      zh: '空气净化器',
      ta: 'காற்று சுத்திகரிப்பான்',
    },
    description: {
      en: 'HEPA air purifier for clean and fresh indoor air',
      ms: 'Penapis udara HEPA untuk udara dalaman yang bersih dan segar',
      zh: 'HEPA空气净化器，保持室内空气清新',
      ta: 'சுத்தமான மற்றும் புதிய உள்ளக காற்றுக்கான HEPA காற்று சுத்திகரிப்பான்',
    },
    category: 'electronics',
    priority: 'medium',
    priceRange: 'RM300 - RM1000',
    quantityTotal: 1,
  },
  {
    id: 'robot-vacuum',
    name: {
      en: 'Robot Vacuum',
      ms: 'Vakum Robot',
      zh: '扫地机器人',
      ta: 'ரோபோ வெற்றிடம்',
    },
    description: {
      en: 'Smart robot vacuum for automated floor cleaning',
      ms: 'Vakum robot pintar untuk pembersihan lantai automatik',
      zh: '智能扫地机器人，自动清洁地板',
      ta: 'தானியங்கி தரை சுத்தம் செய்ய ஸ்மார்ட் ரோபோ வெற்றிடம்',
    },
    category: 'electronics',
    priority: 'medium',
    priceRange: 'RM500 - RM2000',
    quantityTotal: 1,
  },
  {
    id: 'coffee-machine',
    name: {
      en: 'Coffee Machine',
      ms: 'Mesin Kopi',
      zh: '咖啡机',
      ta: 'காபி இயந்திரம்',
    },
    description: {
      en: 'Automatic coffee machine for barista-quality coffee at home',
      ms: 'Mesin kopi automatik untuk kopi berkualiti barista di rumah',
      zh: '自动咖啡机，在家享受咖啡师级别的咖啡',
      ta: 'வீட்டில் பரிஸ்டா-தரமான காபிக்கான தானியங்கி காபி இயந்திரம்',
    },
    category: 'electronics',
    priority: 'medium',
    priceRange: 'RM300 - RM1500',
    quantityTotal: 1,
  },
  {
    id: 'stand-mixer',
    name: {
      en: 'Stand Mixer',
      ms: 'Pengadun Berdiri',
      zh: '立式搅拌机',
      ta: 'ஸ்டாண்ட் மிக்சர்',
    },
    description: {
      en: 'Professional stand mixer for baking and cooking',
      ms: 'Pengadun berdiri profesional untuk membakar dan memasak',
      zh: '专业立式搅拌机，用于烘焙和烹饪',
      ta: 'பேக்கிங் மற்றும் சமையலுக்கான தொழில்முறை ஸ்டாண்ட் மிக்சர்',
    },
    category: 'electronics',
    priority: 'low',
    priceRange: 'RM400 - RM1500',
    quantityTotal: 1,
  },
  {
    id: 'washing-machine',
    name: {
      en: 'Washing Machine',
      ms: 'Mesin Basuh',
      zh: '洗衣机',
      ta: 'சலவை இயந்திரம்',
    },
    description: {
      en: 'Front or top load washing machine for laundry',
      ms: 'Mesin basuh muatan hadapan atau atas untuk dobi',
      zh: '前置或顶置洗衣机',
      ta: 'சலவைக்கான முன் அல்லது மேல் சுமை சலவை இயந்திரம்',
    },
    category: 'electronics',
    priority: 'high',
    priceRange: 'RM800 - RM2500',
    quantityTotal: 1,
  },
  {
    id: 'refrigerator',
    name: {
      en: 'Refrigerator',
      ms: 'Peti Sejuk',
      zh: '冰箱',
      ta: 'குளிர்சாதன பெட்டி',
    },
    description: {
      en: 'Energy-efficient refrigerator for food storage',
      ms: 'Peti sejuk cekap tenaga untuk penyimpanan makanan',
      zh: '节能冰箱，用于食品储存',
      ta: 'உணவு சேமிப்புக்கான ஆற்றல் திறன் குளிர்சாதன பெட்டி',
    },
    category: 'electronics',
    priority: 'high',
    priceRange: 'RM1500 - RM4000',
    quantityTotal: 1,
  },
  {
    id: 'air-conditioner',
    name: {
      en: 'Air Conditioner',
      ms: 'Penyaman Udara',
      zh: '空调',
      ta: 'குளிரூட்டி',
    },
    description: {
      en: 'Energy-efficient air conditioner for comfortable living',
      ms: 'Penyaman udara cekap tenaga untuk kehidupan selesa',
      zh: '节能空调，舒适生活',
      ta: 'வசதியான வாழ்க்கைக்கான ஆற்றல் திறன் குளிரூட்டி',
    },
    category: 'electronics',
    priority: 'high',
    priceRange: 'RM1000 - RM3000',
    quantityTotal: 1,
  },
  {
    id: 'water-heater',
    name: {
      en: 'Water Heater',
      ms: 'Pemanas Air',
      zh: '热水器',
      ta: 'நீர் சூடேற்றி',
    },
    description: {
      en: 'Instant or storage water heater for bathroom',
      ms: 'Pemanas air segera atau simpanan untuk bilik mandi',
      zh: '即热式或储水式热水器',
      ta: 'குளியலறைக்கான உடனடி அல்லது சேமிப்பு நீர் சூடேற்றி',
    },
    category: 'electronics',
    priority: 'high',
    priceRange: 'RM200 - RM800',
    quantityTotal: 1,
  },
  {
    id: 'bluetooth-speaker',
    name: {
      en: 'Bluetooth Speaker',
      ms: 'Pembesar Suara Bluetooth',
      zh: '蓝牙音箱',
      ta: 'புளூடூத் ஸ்பீக்கர்',
    },
    description: {
      en: 'Portable Bluetooth speaker for music and entertainment',
      ms: 'Pembesar suara Bluetooth mudah alih untuk muzik dan hiburan',
      zh: '便携式蓝牙音箱，用于音乐和娱乐',
      ta: 'இசை மற்றும் பொழுதுபோக்கிற்கான கையடக்க புளூடூத் ஸ்பீக்கர்',
    },
    category: 'electronics',
    priority: 'low',
    priceRange: 'RM100 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'hair-dryer',
    name: {
      en: 'Hair Dryer',
      ms: 'Pengering Rambut',
      zh: '吹风机',
      ta: 'முடி உலர்த்தி',
    },
    description: {
      en: 'Professional hair dryer for quick styling',
      ms: 'Pengering rambut profesional untuk penggayaan cepat',
      zh: '专业吹风机，快速造型',
      ta: 'விரைவான ஸ்டைலிங்கிற்கான தொழில்முறை முடி உலர்த்தி',
    },
    category: 'electronics',
    priority: 'low',
    priceRange: 'RM80 - RM300',
    quantityTotal: 1,
  },

  // ============================================
  // EXPERIENCES CATEGORY (9 items)
  // ============================================
  {
    id: 'honeymoon-contribution',
    name: {
      en: 'Honeymoon Contribution',
      ms: 'Sumbangan Bulan Madu',
      zh: '蜜月贡献',
      ta: 'தேனிலவு பங்களிப்பு',
    },
    description: {
      en: 'Contribute to our dream honeymoon adventure',
      ms: 'Sumbang kepada pengembaraan bulan madu impian kami',
      zh: '为我们梦想的蜜月之旅贡献一份力量',
      ta: 'எங்கள் கனவு தேனிலவு சாகசத்திற்கு பங்களிக்கவும்',
    },
    category: 'experiences',
    priority: 'high',
    priceRange: 'RM100 - RM1000',
    quantityTotal: 10,
  },
  {
    id: 'spa-voucher',
    name: {
      en: 'Spa Voucher',
      ms: 'Baucar Spa',
      zh: 'Spa代金券',
      ta: 'ஸ்பா வவுச்சர்',
    },
    description: {
      en: 'Relaxing spa experience voucher for the couple',
      ms: 'Baucar pengalaman spa santai untuk pasangan',
      zh: '情侣放松Spa体验代金券',
      ta: 'தம்பதியருக்கான நிதானமான ஸ்பா அனுபவ வவுச்சர்',
    },
    category: 'experiences',
    priority: 'medium',
    priceRange: 'RM200 - RM500',
    quantityTotal: 2,
  },
  {
    id: 'restaurant-voucher',
    name: {
      en: 'Restaurant Voucher',
      ms: 'Baucar Restoran',
      zh: '餐厅代金券',
      ta: 'உணவகம் வவுச்சர்',
    },
    description: {
      en: 'Fine dining experience voucher for a romantic dinner',
      ms: 'Baucar pengalaman makan malam romantik',
      zh: '浪漫晚餐的精致餐厅体验代金券',
      ta: 'காதல் இரவு உணவுக்கான சிறந்த உணவு அனுபவ வவுச்சர்',
    },
    category: 'experiences',
    priority: 'medium',
    priceRange: 'RM150 - RM400',
    quantityTotal: 2,
  },
  {
    id: 'photography-session',
    name: {
      en: 'Photography Session',
      ms: 'Sesi Fotografi',
      zh: '摄影会话',
      ta: 'புகைப்படம் அமர்வு',
    },
    description: {
      en: 'Professional photography session to capture special moments',
      ms: 'Sesi fotografi profesional untuk merakam detik istimewa',
      zh: '专业摄影会话，捕捉特别时刻',
      ta: 'சிறப்பு தருணங்களை படமெடுக்க தொழில்முறை புகைப்படம் அமர்வு',
    },
    category: 'experiences',
    priority: 'low',
    priceRange: 'RM300 - RM1000',
    quantityTotal: 1,
  },
  {
    id: 'cooking-class',
    name: {
      en: 'Cooking Class',
      ms: 'Kelas Memasak',
      zh: '烹饪课程',
      ta: 'சமையல் வகுப்பு',
    },
    description: {
      en: 'Cooking class experience for the couple to learn together',
      ms: 'Pengalaman kelas memasak untuk pasangan belajar bersama',
      zh: '情侣一起学习的烹饪课程体验',
      ta: 'தம்பதியர் ஒன்றாக கற்றுக்கொள்ள சமையல் வகுப்பு அனுபவம்',
    },
    category: 'experiences',
    priority: 'low',
    priceRange: 'RM150 - RM400',
    quantityTotal: 1,
  },
  {
    id: 'travel-voucher',
    name: {
      en: 'Travel Voucher',
      ms: 'Baucar Perjalanan',
      zh: '旅行代金券',
      ta: 'பயண வவுச்சர்',
    },
    description: {
      en: 'Travel voucher for flights or accommodation',
      ms: 'Baucar perjalanan untuk penerbangan atau penginapan',
      zh: '机票或住宿旅行代金券',
      ta: 'விமானம் அல்லது தங்குமிடத்திற்கான பயண வவுச்சர்',
    },
    category: 'experiences',
    priority: 'medium',
    priceRange: 'RM200 - RM1000',
    quantityTotal: 5,
  },
  {
    id: 'staycation',
    name: {
      en: 'Staycation Package',
      ms: 'Pakej Penginapan',
      zh: '宅度假套餐',
      ta: 'ஸ்டேகேஷன் பேக்கேஜ்',
    },
    description: {
      en: 'Hotel staycation package for a relaxing getaway',
      ms: 'Pakej penginapan hotel untuk percutian santai',
      zh: '酒店宅度假套餐，放松身心',
      ta: 'ஓய்வான விடுமுறைக்கான ஹோட்டல் ஸ்டேகேஷன் பேக்கேஜ்',
    },
    category: 'experiences',
    priority: 'medium',
    priceRange: 'RM300 - RM800',
    quantityTotal: 2,
  },
  {
    id: 'movie-date',
    name: {
      en: 'Movie Date Package',
      ms: 'Pakej Temu Janji Wayang',
      zh: '电影约会套餐',
      ta: 'திரைப்பட டேட் பேக்கேஜ்',
    },
    description: {
      en: 'Movie tickets and dinner voucher for date nights',
      ms: 'Tiket wayang dan baucar makan malam untuk temu janji',
      zh: '电影票和晚餐券，用于约会之夜',
      ta: 'டேட் நைட்ஸுக்கான திரைப்பட டிக்கெட்டுகள் மற்றும் இரவு உணவு வவுச்சர்',
    },
    category: 'experiences',
    priority: 'low',
    priceRange: 'RM100 - RM300',
    quantityTotal: 3,
  },
  {
    id: 'theme-park',
    name: {
      en: 'Theme Park Tickets',
      ms: 'Tiket Taman Tema',
      zh: '主题公园门票',
      ta: 'தீம் பார்க் டிக்கெட்டுகள்',
    },
    description: {
      en: 'Theme park tickets for a fun day out together',
      ms: 'Tiket taman tema untuk hari yang menyeronokkan bersama',
      zh: '主题公园门票，一起度过欢乐的一天',
      ta: 'ஒன்றாக வேடிக்கையான நாளுக்கான தீம் பார்க் டிக்கெட்டுகள்',
    },
    category: 'experiences',
    priority: 'low',
    priceRange: 'RM150 - RM400',
    quantityTotal: 1,
  },

  // ============================================
  // OTHER CATEGORY (12 items)
  // ============================================
  {
    id: 'cash-contribution',
    name: {
      en: 'Cash Contribution',
      ms: 'Sumbangan Wang',
      zh: '现金贡献',
      ta: 'பண பங்களிப்பு',
    },
    description: {
      en: 'Monetary gift to help us start our new life together',
      ms: 'Hadiah wang untuk membantu kami memulakan kehidupan baru bersama',
      zh: '金钱礼物帮助我们开始新生活',
      ta: 'எங்கள் புதிய வாழ்க்கையைத் தொடங்க உதவும் பண பரிசு',
    },
    category: 'other',
    priority: 'high',
    priceRange: 'RM50 - RM500',
    quantityTotal: 10,
  },
  {
    id: 'gym-membership',
    name: {
      en: 'Gym Membership',
      ms: 'Keahlian Gimnasium',
      zh: '健身房会员资格',
      ta: 'ஜிம் உறுப்பினர்',
    },
    description: {
      en: 'Gym membership for a healthy lifestyle together',
      ms: 'Keahlian gimnasium untuk gaya hidup sihat bersama',
      zh: '健身房会员资格，一起享受健康生活',
      ta: 'ஆரோக்கியமான வாழ்க்கை முறைக்கான ஜிம் உறுப்பினர்',
    },
    category: 'other',
    priority: 'low',
    priceRange: 'RM200 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'plant-garden-set',
    name: {
      en: 'Plant & Garden Set',
      ms: 'Set Pokok & Taman',
      zh: '植物和花园套装',
      ta: 'தாவர மற்றும் தோட்ட தொகுப்பு',
    },
    description: {
      en: 'Indoor plants and gardening set to brighten your home',
      ms: 'Pokok dalaman dan set berkebun untuk menceriakan rumah anda',
      zh: '室内植物和园艺套装，点亮您的家',
      ta: 'உங்கள் வீட்டை பிரகாசமாக்க உட்புற தாவரங்கள் மற்றும் தோட்டக்கலை தொகுப்பு',
    },
    category: 'other',
    priority: 'low',
    priceRange: 'RM100 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'prayer-mat-set',
    name: {
      en: 'Prayer Mat Set',
      ms: 'Set Sejadah',
      zh: '祈祷垫套装',
      ta: 'பிரார்த்தனை பாய் தொகுப்பு',
    },
    description: {
      en: 'Beautiful prayer mat set for spiritual practice',
      ms: 'Set sejadah cantik untuk amalan kerohanian',
      zh: '美丽的祈祷垫套装，用于灵修',
      ta: 'ஆன்மீக பயிற்சிக்கான அழகான பிரார்த்தனை பாய் தொகுப்பு',
    },
    category: 'other',
    priority: 'medium',
    priceRange: 'RM50 - RM200',
    quantityTotal: 2,
  },
  {
    id: 'luggage-set',
    name: {
      en: 'Luggage Set',
      ms: 'Set Beg Bagasi',
      zh: '行李箱套装',
      ta: 'லக்கேஜ் தொகுப்பு',
    },
    description: {
      en: 'Quality luggage set for travel and honeymoon',
      ms: 'Set beg bagasi berkualiti untuk perjalanan dan bulan madu',
      zh: '高品质行李箱套装，用于旅行和蜜月',
      ta: 'பயணம் மற்றும் தேனிலவுக்கான தரமான லக்கேஜ் தொகுப்பு',
    },
    category: 'other',
    priority: 'medium',
    priceRange: 'RM300 - RM1000',
    quantityTotal: 1,
  },
  {
    id: 'first-aid-kit',
    name: {
      en: 'First Aid Kit',
      ms: 'Kit Pertolongan Cemas',
      zh: '急救箱',
      ta: 'முதலுதவி பெட்டி',
    },
    description: {
      en: 'Comprehensive first aid kit for home safety',
      ms: 'Kit pertolongan cemas lengkap untuk keselamatan rumah',
      zh: '全面的家庭安全急救箱',
      ta: 'வீட்டு பாதுகாப்புக்கான விரிவான முதலுதவி பெட்டி',
    },
    category: 'other',
    priority: 'low',
    priceRange: 'RM50 - RM150',
    quantityTotal: 1,
  },
  {
    id: 'tool-kit',
    name: {
      en: 'Home Tool Kit',
      ms: 'Kit Alat Rumah',
      zh: '家用工具套装',
      ta: 'வீட்டு கருவி பெட்டி',
    },
    description: {
      en: 'Essential tool kit for home repairs and DIY projects',
      ms: 'Kit alat penting untuk pembaikan rumah dan projek DIY',
      zh: '家居维修和DIY项目的必备工具套装',
      ta: 'வீட்டு பழுது மற்றும் DIY திட்டங்களுக்கான அத்தியாவசிய கருவி பெட்டி',
    },
    category: 'other',
    priority: 'medium',
    priceRange: 'RM80 - RM300',
    quantityTotal: 1,
  },
  {
    id: 'charity-donation',
    name: {
      en: 'Charity Donation',
      ms: 'Sumbangan Amal',
      zh: '慈善捐款',
      ta: 'தர்ம நன்கொடை',
    },
    description: {
      en: 'Donation to a charity of our choice in lieu of gifts',
      ms: 'Sumbangan kepada badan amal pilihan kami sebagai ganti hadiah',
      zh: '代替礼物捐赠给我们选择的慈善机构',
      ta: 'பரிசுகளுக்கு பதிலாக நாங்கள் தேர்ந்தெடுக்கும் தர்ம நிறுவனத்திற்கு நன்கொடை',
    },
    category: 'other',
    priority: 'medium',
    priceRange: 'RM50 - RM500',
    quantityTotal: 10,
  },
  {
    id: 'quran-set',
    name: {
      en: 'Quran Set',
      ms: 'Set Al-Quran',
      zh: '古兰经套装',
      ta: 'குர்ஆன் தொகுப்பு',
    },
    description: {
      en: 'Beautiful Quran set with translation and tafsir',
      ms: 'Set Al-Quran cantik dengan terjemahan dan tafsir',
      zh: '带翻译和注释的精美古兰经套装',
      ta: 'மொழிபெயர்ப்பு மற்றும் விளக்கத்துடன் அழகான குர்ஆன் தொகுப்பு',
    },
    category: 'other',
    priority: 'high',
    priceRange: 'RM100 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'perfume-set',
    name: {
      en: 'Perfume Set',
      ms: 'Set Minyak Wangi',
      zh: '香水套装',
      ta: 'வாசனை திரவியம் தொகுப்பு',
    },
    description: {
      en: 'Luxury perfume set for him and her',
      ms: 'Set minyak wangi mewah untuk lelaki dan wanita',
      zh: '奢华香水套装，男女皆宜',
      ta: 'அவருக்கும் அவளுக்கும் ஆடம்பர வாசனை திரவியம் தொகுப்பு',
    },
    category: 'other',
    priority: 'low',
    priceRange: 'RM150 - RM500',
    quantityTotal: 1,
  },
  {
    id: 'watch-set',
    name: {
      en: 'Couple Watch Set',
      ms: 'Set Jam Tangan Pasangan',
      zh: '情侣手表套装',
      ta: 'தம்பதி கடிகாரம் தொகுப்பு',
    },
    description: {
      en: 'Matching couple watch set for him and her',
      ms: 'Set jam tangan pasangan sepadan untuk lelaki dan wanita',
      zh: '情侣配对手表套装',
      ta: 'அவருக்கும் அவளுக்கும் பொருத்தமான தம்பதி கடிகாரம் தொகுப்பு',
    },
    category: 'other',
    priority: 'medium',
    priceRange: 'RM200 - RM1000',
    quantityTotal: 1,
  },
  {
    id: 'home-decor',
    name: {
      en: 'Home Decor Set',
      ms: 'Set Hiasan Rumah',
      zh: '家居装饰套装',
      ta: 'வீட்டு அலங்கார தொகுப்பு',
    },
    description: {
      en: 'Decorative items to beautify your new home',
      ms: 'Barangan hiasan untuk mencantikkan rumah baru anda',
      zh: '装饰物品，美化您的新家',
      ta: 'உங்கள் புதிய வீட்டை அழகுபடுத்த அலங்கார பொருட்கள்',
    },
    category: 'other',
    priority: 'low',
    priceRange: 'RM100 - RM400',
    quantityTotal: 1,
  },
]

// Helper function to get templates by category
export function getDefaultGiftsByCategory(category: GiftCategory | 'all'): DefaultGiftTemplate[] {
  if (category === 'all') {
    return DEFAULT_GIFT_TEMPLATES
  }
  return DEFAULT_GIFT_TEMPLATES.filter((gift) => gift.category === category)
}

// Get count per category
export function getDefaultGiftCounts(): Record<GiftCategory | 'all', number> {
  const counts: Record<GiftCategory | 'all', number> = {
    all: DEFAULT_GIFT_TEMPLATES.length,
    home: 0,
    kitchen: 0,
    electronics: 0,
    experiences: 0,
    other: 0,
  }

  for (const gift of DEFAULT_GIFT_TEMPLATES) {
    counts[gift.category]++
  }

  return counts
}
